# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a6582a4d306c020748916109ba84b8d9c08fbb768654d432a3e3a5ac532ac2e1813a139a0aafeb63216824554c76a51654432cfcb1de1dc22ef21499e564552f

test:
  secret_key_base: 528b494d5fc25d6ae958df816a74b436c1b89a112aa9e53cc82030f65c0ef7c1a62675eb67d928ff764f6dc9cb4a717022f9892cb47798dce03481ab87c9e435

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
